apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  ports:
  - port: 16686
    targetPort: 16686
    name: jaeger-ui
  - port: 14250
    targetPort: 14250
    name: grpc-collector
  - port: 6831
    targetPort: 6831
    protocol: UDP
    name: jaeger-agent
  selector:
    app: jaeger